// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Identifies a plant from a picture and provides a description.
 *
 * - identifyPlant - A function that handles the plant identification process.
 * - IdentifyPlantInput - The input type for the identifyPlant function.
 * - IdentifyPlantOutput - The return type for the identifyPlant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyPlantInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a plant, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type IdentifyPlantInput = z.infer<typeof IdentifyPlantInputSchema>;

const IdentifyPlantOutputSchema = z.object({
  isPlant: z.boolean().describe("Whether or not the image contains a plant."),
  scientificName: z.string().describe('The scientific name of the plant. Returns "N/A" if not a plant.'),
  commonName: z.string().describe('The common name of the plant. Returns "N/A" if not a plant.'),
  habitat: z.string().describe('The natural environment of the plant. Returns "N/A" if not a plant.'),
  species: z.string().describe('The species of the plant. Returns "N/A" if not a plant.'),
  lifespan: z.string().describe('The typical lifespan of the plant. Returns "N/A" if not a plant.'),
  description: z.string().describe('A detailed description of the plant, or a description of what is in the image if it is not a plant.'),
});
export type IdentifyPlantOutput = z.infer<typeof IdentifyPlantOutputSchema>;

export async function identifyPlant(input: IdentifyPlantInput): Promise<IdentifyPlantOutput> {
  return identifyPlantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyPlantPrompt',
  input: {schema: IdentifyPlantInputSchema},
  output: {schema: IdentifyPlantOutputSchema},
  prompt: `You are a botanist. Given a picture, determine if it contains a plant.
  
  If the image contains a plant, identify it and provide a detailed description. Set isPlant to true and fill in the other fields.

  If the image does NOT contain a plant, set isPlant to false, set the string fields to "N/A", and briefly describe what is in the image in the description field.
  
  Photo: {{media url=photoDataUri}}`,
});

const identifyPlantFlow = ai.defineFlow(
  {
    name: 'identifyPlantFlow',
    inputSchema: IdentifyPlantInputSchema,
    outputSchema: IdentifyPlantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
