// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Identifies a plant from a picture and provides a description.
 *
 * - identifyPlant - A function that handles the plant identification process.
 * - IdentifyPlantInput - The input type for the identifyPlant function.
 * - IdentifyPlantOutput - The return type for the identifyPlant function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyPlantInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a plant, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type IdentifyPlantInput = z.infer<typeof IdentifyPlantInputSchema>;

const IdentifyPlantOutputSchema = z.object({
  scientificName: z.string().describe('The scientific name of the plant.'),
  commonName: z.string().describe('The common name of the plant.'),
  habitat: z.string().describe('The natural environment of the plant.'),
  species: z.string().describe('The species of the plant.'),
  lifespan: z.string().describe('The typical lifespan of the plant.'),
  description: z.string().describe('A detailed description of the plant.'),
});
export type IdentifyPlantOutput = z.infer<typeof IdentifyPlantOutputSchema>;

export async function identifyPlant(input: IdentifyPlantInput): Promise<IdentifyPlantOutput> {
  return identifyPlantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyPlantPrompt',
  input: {schema: IdentifyPlantInputSchema},
  output: {schema: IdentifyPlantOutputSchema},
  prompt: `You are a botanist. Given a picture of a plant, identify the plant and provide a detailed description of it.

  Please provide the scientific name, common name, habitat, species, lifespan, and a detailed description of the plant.
  Photo: {{media url=photoDataUri}}`,
});

const identifyPlantFlow = ai.defineFlow(
  {
    name: 'identifyPlantFlow',
    inputSchema: IdentifyPlantInputSchema,
    outputSchema: IdentifyPlantOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
